### ISSUE TITLE
Disc not working

### ISSUE THREAD

**Issue by bodhi-baum** [stardot/b-em#131]
Running latest b-em under Linux. Trying to see a directory via *CAT or *. lets the floppy sound occure but nothing more happens and the program does nothing more.

**Comment by SteveFosdick** [comment]
Can you help me reproduce this, please?  What disc image have you loaded into the drive?  If it's not a common one, can you attach it to this bug report?  What model are you emulating when this happens?  Could you check which DFS/ADFS version is running with *HELP?

**Comment by bodhi-baum** [comment]
Hello, I did a bit of testing and this are the results: 
Working: BBC B w/8271 FDC, BBC B w/opus 1770 FDC, BBC B w/ Solidisc 1770 FDC, BBC B w/watford 1770 FDC, BBC B+ 128k, BBC B+ 64k, BBC B, 65C02, Acorn 1770, BBC Master 128, BBC Master 128 w/MOS 3.22, BBC Master 128 w/MOS 3.5, BBC Master 128 w/MOS 3.52 and BBC Master Turbo 

Not working: BBC B German, BBc w/1770 FDC, BBC B w/OS 0.1, BBC B with 65C02, no FDC

BBC Master 512 shows Disc error 50 at :0/000000

I used an .ssd for all of this. Hope this helps.

**Comment by bodhi-baum** [comment]
As I´m not familiar with BBC Micro I don´t know if it maybe is normal for some models not to react, but that BBC w/1770 FDC should work as it has a FDC 1770 drive emulated, shouldn´t it?

**Comment by SteveFosdick** [comment]
You're right that some of these don't work with disc.

OS 0.1 did not support sideways ROM and, as DFS is implemented as a sideways ROM, discs won't work with OS 0.1.

BBC B with 65C02 and no FDC doesn't have a floppy disc controller chip at all and no DFS in the ROM configuration.  As a B-Em emulated machine it is designed for use with VDFS, a filing system that shares the host's files rather than working with disc images.  It would also work with tape.

The Master 512 has an 80186 2nd processor and will try to boot into DOS so that won't work if the disc you have loaded is not a DOS disc for that 2nd processor.

The others I will look into later.

**Comment by SteveFosdick** [comment]
Ok, testing the ones where I know of no reason why they should not work, each case using the Welcone Disc as the test as this image comes with B-Em.

Gernan BBC B:
![ss1](https://user-images.githubusercontent.com/1048671/105643820-14a83d80-5e8a-11eb-8ca6-c905610ebd23.png)
then
![ss2](https://user-images.githubusercontent.com/1048671/105643827-1bcf4b80-5e8a-11eb-861f-36af38cce961.png)

BBC B with WD1770:
![ss3](https://user-images.githubusercontent.com/1048671/105643835-28ec3a80-5e8a-11eb-8a36-b53d04359537.png)
then
![ss4](https://user-images.githubusercontent.com/1048671/105643837-2d185800-5e8a-11eb-95a0-a5dafd7d5e23.png)

Which SSD are you using?  Can you attach it?  Or can you re-test these models to see if you get the same results I do with the bundled welcome disc.

**Comment by bodhi-baum** [comment]
Where do I find this welcme disc?

**Comment by bodhi-baum** [comment]
Here is the file I used anyway.
[Disc157-TrickysoftPacManCB.ssd.zip](https://github.com/stardot/b-em/files/5864603/Disc157-TrickysoftPacManCB.ssd.zip)

**Comment by SteveFosdick** [comment]
The welcome disc is bundle with B-Em in the discs directory as you clone it from GitHub.

The Tricky PacMan game on that disc works fine for me using the Models you were having trouble but which are supposed to work: German BBC B and Model B with WD1770.

When you say the disc noise starts and nothing further happens, does the disc noise continue all the time nothing else is happening, or does it stop again?

**Comment by bodhi-baum** [comment]
Hmm, I'm a bit embarrassed, but now it works for me too. I must have made a mistake in operating the programme. As they say in German: "Das Problem sitzt meist vor dem Monitor".

**Comment by bodhi-baum** [comment]
The noise stops,btw.

**Comment by SteveFosdick** [comment]
If the noise stops really quickly it is possible that this could be caused by file locking.  On Linux, as the disc spins up b-em takes out an advisory file lock on the SSD file.  This is so if you have another instance of b-em running also with the same disc image loaded, only one of them accesses it at once and there is no corruption.  The lock is released when the disc spins down.

If the problem comes back, to see if file locking is the cause, you could execute the 'lslocks' command in a terminal window and check the output.  If you need help you could post the output here.
