### ISSUE TITLE
B-em Econet branch wont build on Mac os  x

### ISSUE THREAD

**Issue by sai2791** [stardot/b-em#145]
Compiler error follows.

vdfs.c:2742:30: warning: result of comparison of constant 4294901760 with expression of type 'uint16_t' (aka 'unsigned short') is always false
      [-Wtautological-constant-out-of-range-compare]
                    if (addr > 0xffff0000 || curtube == -1) {
                        ~~~~ ^ ~~~~~~~~~~
1 warning generated.
  CC       b_em-via.o
  CC       b_em-vidalleg.o
  CC       b_em-video.o
  CC       b_em-wd1770.o
  CC       b_em-x86.o
  CXXLD    b-em
Undefined symbols for architecture x86_64:
  "_log_debug", referenced from:
      _os_paste_start in b_em-6502.o
      _do_readmem in b_em-6502.o
      _do_writemem in b_em-6502.o
      _m6502_reset in b_em-6502.o
      _dumpregs in b_em-6502.o
      _EconetReset in b_em-econet.o
      _Read_Econet_Station in b_em-econet.o
      ...
  "_log_dump", referenced from:
      _EconetPoll_real in b_em-econet.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:707: b-em] Error 1
make[1]: Leaving directory '/Users/steveinglis/Documents/b-em/src'
make: *** [Makefile:427: all-recursive] Error 1

Removing the conditional lines in logging.h does allow the application to compile

// If the debugging compilation option is enabled a real function will
// be available to log debug messages.  If the debugging compilation
// optionis disabled we use a static inline empty function to make the
// debug calls disappear but in a way that does not generate warnings
// about unused variables etc.

static inline void log_debug(const char *format, ...) printflike;
static inline void log_debug(const char *format, ...) {}
static inline void log_dump(const char *prefix, uint8_t *data, size_t size) {}

I have not seen this construct before so I am not sure how to go about fixing it

**Comment by SteveFosdick** [comment]
When you say "I have not seen this construct before so I am not sure how to go about fixing it" do you mean a empty static inline function like:
```
static inline void log_debug(const char *format, ...) {}
```

It is quite common to use the pre-processor to make calls to log debug information disappear by defining what would otherwise be a function to an empty macro but that can cause compiler warnings when the value of a variable is only used by a debug logging statement.

This syntax avoids this.  The combination of static and inline means the compiler should only inline the function and not generate an actual function body.  Then, as the function is empty, the compiler will, with luck, also optimise away the calculation of its arguments but in a way that doesn't generate the warning.

The only odd bit is the trailing printflike which should be #defined earlier in the file but only on gcc - for other compilers it should be empty.  It's a compiler hint to say the function uses a printf format string so the compiler can check the format string against the arguments.  If there is an equivalent for clang it would be good to enable it there too.

**Comment by SteveFosdick** [comment]
Also, it is probably worth trying the sf/econet2 branch instead of the sf/econet one.

**Comment by SteveFosdick** [comment]
And some more detail on the debugging business.  When running ./configure one can choose to enable debugging or not and this sets _DEBUG  This works quite well until you update header files for the thing you're working on and make then re-compiles other parts of the project which now also start logging debug messages too making it harder to see the wood for the trees.

So I temporarily added #define _DEBUG to the top of the econet.c module (and at one point 6502.c too) to get debug messages for only those modules but to make it compile you have to do the same to logging.c otherwise the called functions don't exist.  I may have inadvertently committed the tempory change to econet.c to the repository and not the one to logging.c

**Comment by sai2791** [comment]
I can confirm that when #define _DEBUG is added to the logging.h b-em (sf/econet2) builds fine. I will see if I can find a clang equivalent for the inline stuff, and thanks for taking the time to explain it.

**Comment by sai2791** [comment]
There is absolutely nothing wrong the the code in logging.h it is the same for clang and the gnu c compiler, what seems to be causing the problems on the mac is that the 6502.c and econet.c have #define _DEBUG and are missing #include "logging.h".  Since you seem to be doing work on these did you want me to create a pull request, or just leave it until you are done?

Also, quick question on the econet version, how do you get the emulator to recognise that the clock is active.  I kept getting No Clock.

**Comment by SteveFosdick** [comment]
Steve, if not logging.h then logging.c.  My intention was that none of the files would have #define _DEBUG as checked into the repository, that was just a hack for what I was doing.

For the clock it depends on whether b-em succeeds in opening the socket.  If it does it raises the appropriate line to the 6854 and DNFS see that as clock detected.  Otherwise it doesn't and DNFS reports no clock.

**Comment by SteveFosdick** [comment]
Have a look at lines 640 onwards of econet.c and see if any of those message are logged to stderr or appear in the log $HOME/.config/b-em/b-emlog.txt
