### ISSUE TITLE
Code adjustements for W10/MinGW64 build

### ISSUE THREAD

**Issue by pstnotpd** [stardot/b-em#23]
While attempting a build I noticed some issues which only seem to occur on this newer version of the compiler.

- tsearch.c contains a typedef for max_allign_t which now seems to be already done in the standard headers, or the surrounding #ifndef text must have changed 
`/*
#ifndef __CLANG_MAX_ALIGN_T_DEFINED
typedef long double max_align_t;
#endif
*/
`
- Makebem.bat points hardcoded to C:/Mingw where in Msys2 we have C:\msys64\mingw32 and mingw64
`set `MINGW=c:\MinGW`. Also, a makebem.sh seems more natural but preferably the autogen part should work.
`
- Compling Z80.c fails because in the Makefile.win it is actually called z80.c (lower case). Somehow this compiler version is case-sensitive.

**Comment by ThomasAdam** [comment]
Hi,

Thanks.  Are you able to open a pull-request which looks to address these issues?

**Comment by pstnotpd** [comment]
Yes I will, but I think we must have a neater solution to the max_allign_t typedef issue. I've forked the repository now and continue from there as per instruction.

Meanwhile, how can I contribute to the wiki? Is appears to be a seperate repository which does not fork and it doesn't allow me to push to the master.

**Comment by hoglet67** [comment]
I've opened up the Wiki to edits from any authenticated user. So you should be able to create a new page now.

**Comment by SteveFosdick** [comment]
I think I have a solution to the max_allign_t typedef.  It seems this was introduced in C11 and for the previous MingW version of gcc that is not the default standard level meaning it is undefined and tsearch.c has to include its own declaration.  The MingW64 version of gcc by default uses gnu11 as its standard i.e. everything in C11 + GNU extensions so that typedef will then be defined.  So what I think that means is that instead of testing OS or compiler we should test the C standard version to work out whether to include it, i.e. instead of:

```
#ifndef __CLANG_MAX_ALIGN_T_DEFINED
typedef long double max_align_t;
#endif
```
we should have:

```
#if __STDC_VERSION__ < 201112
typedef long double max_align_t;
#endif

```

**Comment by SteveFosdick** [comment]
Dominic Beasley is current working on B-Em in Visual Studio so I am assuming it compiles fine now.
