### ISSUE TITLE
Pause & single step functions

### ISSUE THREAD

**Issue by kieranhj** [stardot/b-em#34]
I extended my own version of b-em to have pause on PAGE DOWN (to complement PAGE UP) and single frame (20ms) step on RIGHT ARROW when paused.  These are both very helpful for debugging, particularly graphical effects.  Would this be useful to integrate into the main repo?

I'm not sure how to do a PR across repos plus don't have the "official" build environment set up on my machine to properly test - just a hacked together Visual Studio solution.

The small changes are here: https://github.com/kieranhj/b-em/commit/7adb94f7124e3bdfa93e7ef6257376b6a0a6d496

**Comment by SteveFosdick** [comment]
Ok, I will have a look later.

**Comment by SteveFosdick** [comment]
OK, so when I looked at this the pause feature was indeed on Windows only.

It looks like it may have been introduced originally because the Windows port runs the actual emulation on one thread, i.e. that _mainthread function, and the UI and other Windows messages in another thread and needed a way to pause the emulation while the UI thread was tinkering with it, i.e. calling reset functions etc.  Hooking pause up to a key was a bonus.

So in the version I have pushed to the sf/pause branch I have moved the implementation from win.c to main.c so it works on Linux too.  I have also added the check for whether paused to the int50 function which is obviously called 50x a second from a timer and indicates. by incrementing fcount, that another frame should be processed so when paused it just doesn't increment it so the main loop will do whatever it does between frames, i.e. call wait(1).  This should also use less CPU when paused as removing the sleep(100) when paused looks like it would busy wait.

There is a tiny bit of extra complexity in that within the context of main.c we only know if a key is down, not that it has just that moment been pressed so it necessary to track the previous state of the key to avoid acting more than once on the same keypress.  I think this is preferable to having two separate implementations (and the Linux one would have to do that anyway).

**Comment by ThomasAdam** [comment]
I had a quick look at that commit.  Again, looks OK, however I would say that:

* Do we really need to keep adding `extern` to the definition of variables in header files?  I'd say not, as it's not needed.
* file-scoped `static` variables (i.e., those not declared `static` inside functions) do not need to be set explicitly to `0` as the compiler will do this (per the ANSI standard).
* There's a *tonne* of whitespace changes here which are really distracting to the diff, not to mention nothing to do with adding a pause.  Again, this is better addressed differently rather than just randomly always letting whitespace changes through.

**Comment by SteveFosdick** [comment]
On the question of 'extern' that is what makes what appears in the header file a declaration rather than a definition.  The header file may be included in more than one module and #including a header is just included text - C has no proper concept of importing modules.  So if the header file has a definition of a variable and the header file is included in multiple C modules then the variable is then defined in multiple modules.  If the linker resolves that by pointing all references to one of those and removes the others then it is being helpful but it is not required to do that, it could just as well complain and not link the program.

On the question of static variables, some people use the '= 0' explicit syntax, which is harmless otherwise, to indicate that code elsewhere relies on the fact this variable starts out as zero whereas in many cases the initial value of a variable is of no consequence.  Not everyone adopts that style but it isn't a broken thing to do.

On the question of the whitespace I didn't do that.  It looks like at some point I turned on an option in Geany to remove trailing spaces from lines because I didn't want them for something I was writing rather than making minor changes to and it has obviously found some cases where a line consists only of spaces and a newline.  If you want prepare a different version that keeps the functional changes but reverts the whitespace then be my guest but I don't propose to spend the time doing it.

**Comment by SteveFosdick** [comment]
This is now merged to master.
