### ISSUE TITLE
Pixels seem to have inconsistent widths on emulated screen

### ISSUE THREAD

**Issue by ZornsLemma** [stardot/b-em#56]
If you look at the attached screenshot, you can see that some of the P characters look different to others. This is with allegro4 on Linux, built from commit 8277fe9333d82e92a52bf57e1bab892921bb799e.

![screenshot](https://user-images.githubusercontent.com/7988240/38118329-e781d8a8-33b1-11e8-9628-d6e757a37365.png)

I have seen similar results using older versions of b-em on Windows. I suspect the cause is that the emulator's window is not a neat multiple of the BBC screen size, so one BBC pixel gets mapped to a fractional number of pixels on the host screen and so some BBC pixels are (say) 2 host pixels wide and some are (say) 3 host pixels wide. On Windows I was able to fix this by using the menus to force the emulated window to an appropriate size, but I don't see any such options on Linux (nor is the window itself resizable)

**Comment by SteveFosdick** [comment]
Interesting.  On the Allegro4 version the code that blits the bitmap from the BBC onto the screen in vidalleg.c is rather different between Windows and Linux.  The Windows code implements window re-sizing, scaling the output as appropriate, but the Linux code does not.  The Linux code is also missing the PAL simulation.  I did look to see if they could be made more similar but allocating a video bitmap on Linux crashes.  AFAIK this is an Allegro bug or a bug in the particular backend Allegro4 uses.

On the Allegro 5 port there is now one set of video blit code with the same options on both platforms.  It chooses an initial window size to get 1:1 and you can re-size it from there.

One test of your theory would be to save a screenshot from B-Em's own menu rather than via the desktop and compare.

**Comment by SteveFosdick** [comment]
See https://github.com/stardot/b-em/commit/1cb9b46e368933eb6e850a49e3f0af1f2dd59b61

Checking the in-line function upscale_only at vidalleg.c line 161 it was upscaling - by two pixels.

**Comment by ZornsLemma** [comment]
Thanks for this. I've had a go with a simple test program to draw a sawtooth wave:
```
10MODE 0
20X%=0
30Y%=0
40IY%=4
50FOR I%=1 TO 1000
60PLOT 69,X%,Y%
70X%=X%+2
80Y%=Y%+IY%
90IF Y%=1020 OR Y%=0 THEN IY%=IY%*-1
100NEXT
```
I've attached screenshots of this from my Linux desktop:.
![line-screenshot-from-linux-desktop](https://user-images.githubusercontent.com/7988240/38136093-1661c14e-3414-11e8-8719-dced81d0334d.png)

and from b-em's own screenshot feature (converted from BMP to PNG format using the 'convert' command line tool to keep github happy):
![line-screenshot-from-b-em-itself](https://user-images.githubusercontent.com/7988240/38136125-52db897a-3414-11e8-9544-c94f33055a35.png)

b-em's own screenshot has much more regular pixels, although it seems to omit the bottom-most row of pixels (the image is 640x510 and the rightmost bottom point of the sawtooth has its tip missing)

I'll see if I can do an Allegro 5 build later and try that.

**Comment by ZornsLemma** [comment]
Looks like https://github.com/stardot/b-em/commit/1cb9b46e368933eb6e850a49e3f0af1f2dd59b61has fixed this for Allegro4, thanks!
![screenshot from 2018-03-30 15-33-51](https://user-images.githubusercontent.com/7988240/38141489-4a31dcf4-3430-11e8-962e-55a87718b9e5.png)

**Comment by ZornsLemma** [comment]
The bottom row of pixels is still missing on the b-em-generated screenshots, FWIW; shall I raise a separate issue for that?

**Comment by SteveFosdick** [comment]
Try the latest commit which should fix the failure to save the last line in a screenshot.

**Comment by ZornsLemma** [comment]
Works a treat, thanks!
