### ISSUE TITLE
Disc drive sound doesn't stop if no disc is inserted

### ISSUE THREAD

**Issue by pau1ie** [stardot/b-em#58]
If you don't insert a disc in the drive but try to use it anyway, the disc drive spinning noise continues until a disc image is entered to that drive.

**Comment by SteveFosdick** [comment]
This should be fixed by https://github.com/stardot/b-em/commit/b8472c0c63cd3e681f91206fa6ebdc6ed5821fac

What happened here is that with the previous version the sound was polled whereas now it handed off to Allegro and continues in the background.  That means the sound needs to be cancelled whenever the motor stops.  There was a bug in that when the disc controller hit an error the motor was stopped instantly (and the sound silenced) but then the DFS wrote to the track register which caused the emulation to think the motor should be re-started but, as this was the last event in the sequence, it never stopped again until a successful disc operation.

The solution is to introduce a short spindown after the error.  The lasts until after the DFS has written to the track register and thus when the motor stops, it stays stopped.

**Comment by pau1ie** [comment]
Latest version tested (Says v2f7024c in the title bar) and noise stops correctly after a disc error. Brilliant!
