### ISSUE TITLE
Screen flicker

### ISSUE THREAD

**Issue by pau1ie** [stardot/b-em#60]
Building the allegro5-pre2 release candidate from source and running in Arch linux, the first two runs after a cold boot give a flickering line at the bottom of the window (Tested twice). Subsequent runs don't exhibit this problem.

I am not totally convinced that this is a b-em problem - it goes away, but raising it anyway just in case.

See this video (Sorry, the focus could be better - let me know if you need me to try to get a better one)
[Google drive link](https://drive.google.com/open?id=1Hbd3vUlUtGSlNPVtLtI_0nBTe6ZwBvq2)

And thank you for your work on b-em. It is a massive improvement over the previous version. I hope you find these reports useful!

**Comment by SteveFosdick** [comment]
I have an idea what may be happening here.  As the window starts to become larger than a 1:1 mapping from BBC pixels to PC pixels, B-Em waits until it is 10 pixels or more bigger in either direction before it starts automatically up-scaling.  This is to make it easy to get back to an exact 1:1 mapping after having had the screen at another size.  But, I don't think those up to ten lines have anything drawn on them so what you see is probably what is in the graphic cards memory.  The flickering is, I think, because the card is probably swapping buffers at each framsync and the contents of each are slightly different.  It looks like my setup was forgiving and the driver initialised new video buffers to all black whereas the driver for your card doesn't.  I'll have to have a closer look tomorrow and also see if I can find another machine here that demonstrates the problem.

In the mean time you could try shrinking the window vertically and see if it disappears.  That would actually be useful to know - if this is what I think it is then the flashing lines should vanish.  If the flashing stays at the bottom of the Window even when it is smaller then it may be something else.

**Comment by SteveFosdick** [comment]
See if https://github.com/stardot/b-em/commit/44f096d7c2c743c931a2322482fd933a726f9878 fixes this.

**Comment by pau1ie** [comment]
Thanks for the quick fix! looks good, but want to reboot and test again as it was somewhat intermittent. though this will have to wait till tomorrow.

**Comment by pau1ie** [comment]
After another reboot, it still looks good, so closing. Thanks!
