### ISSUE TITLE
HDinit.ssd not in distribution.

### ISSUE THREAD

**Issue by afarlie** [stardot/b-em#68]
Readme file refers to an HDInit.ssd progrma used to initalise a Hard disc image. This disc image is not present in the distribution.

**Comment by afarlie** [comment]
I will also note that for some reason the preivew release doesn't like reading the HDinit.ssd supplied with B-EM 2.2 claiming it can't determine the geometry of the relevant disc image.

**Comment by SteveFosdick** [comment]
I have fixed this in commit d189ebd.

The reason B-Em was complaining about the HDInit.ssd disc image is because someone had set the size in sectors within the disc catalogue to 182.  At 10 sectors/track this would mean this disc image would have 18.2 tracks.  The smallest disc that existed on the BBC micro was single-sided, single-density, 40 tracks which had 400 sectors.  B-Em is trying to match the image against an internal table of known disc images and is not finding a match.

So, the image I have pushed in d189ebd I have altered to declare its size as 400 sectors, i.e. SS/SD/40.
